<?php

namespace ShopBundle\Repository;

use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommandeByUser($idUser)
    {
        return $this->getEntityManager()->createQuery('SELECT e
                FROM AppBundle:Commande e
                WHERE e.idUser = :idUser')
            ->setParameter('idUser', $idUser)
            ->getResult();
    }

}
