<?php

namespace ShopBundle\Repository;

use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{


    public function findCommandeByUser($idUser)
    {
        $dql = $this->createQueryBuilder('commande');
        $dql->select()->where('commande.idUser = :idUser')->setParameter('idUser', $idUser);
        $query = $dql->getQuery();
        return $query->getResult();
    }

    public function CountCommande($idUser)
    {
        return $this->createQueryBuilder('commande')

            ->select('COUNT(commande)')

            -> where('commande.idUser = :idUser')->setParameter('idUser', $idUser)

            ->getQuery()

            ->getSingleScalarResult();

    }

}
