<?php

namespace ShopBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT produit 
                FROM AppBundle:Produit produit
                WHERE produit.nom LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function BestSellers()
    {
        $dql = $this->createQueryBuilder('produit');
        $dql->orderBy('produit.NbVentes', 'DESC');
        $query = $dql->getQuery();
        $query->setMaxResults(3);
        return $query->getResult();
    }
}
