<?php

namespace FormationBundle\Repository;

/**
 * FormulaireInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireInscriptionRepository extends \Doctrine\ORM\EntityRepository
{

    public function gettoutlesreservation()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT f.titleF as nom, r.id as rid ,r.dateInscription as date , r.nombrePlaceReservation as nbr ,r.etat as etat , u.id as id , u.username as username  from AppBundle:FormulaireInscription r JOIN AppBundle:Formation f WITH r.idFormation=f.id  JOIN AppBundle:FosUser u WITH r.idUser=u.id");
        return $query->getResult();

    }
}
