<?php

namespace LivraisonBundle\Repository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getstat()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT a.etat,a.idarticle,a.date,a.titre,a.image,a.description, CASE WHEN r.type='Like'THEN r.type ELSE 'none' END as Rated,SUM(CASE WHEN r.type = 'Like' THEN 1 ELSE 0 END ) as likes 
     from BlogBundle:Article a LEFT JOIN BlogBundle:Rating r with a.idarticle=r.article   GROUP BY a.idarticle ORDER BY r.type");

        return $query->getResult();
    }
}
