<?php

namespace EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEvent($user)
    {

        $parameters = array(
            'user' => $user

        );

        $query = $this->getEntityManager()
            ->createQuery("SELECT u.id as idUser , event.id as id, event.title , event.dateDebutEvent , event.dateFinEvent , event.nbrDePlace, event.lieuEvent, event.descriptionEvent, event.image ,CASE  WHEN r.user =:user THEN r.type ELSE 'none' END as Rated ,SUM(CASE WHEN r.type = 'Like' THEN 1 ELSE 0 END ) as likes , SUM(CASE WHEN r.type = 'Dislike' THEN 1 ELSE 0 END ) as dislikes ,
            u.username as user from AppBundle:Event event LEFT JOIN AppBundle:Favorite r with event.id = r.event LEFT JOIN AppBundle:FosUser u with u.id = event.user  GROUP BY event.id")
            ->setParameters($parameters);
        return $query->getResult();
    }
}

