<?php

namespace EventBundle\Repository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLikes()
    {

        $query = $this->getEntityManager()
            ->createQuery("select count(r.id) as cnt from AppBundle:Favorite r WHERE r.type='Like'");
        return $query->getResult();

    }

    public function getFavorite($user,$event)
    {

        $query = $this->createQueryBuilder('r')
            ->where('r.user = :user')
            ->andWhere('r.event = :event')
            ->setParameters(array(
                    'user'=>$user,
                    'event'=>$event,
                )
            )
            ->getQuery();
        return $query->getResult();
    }
}

