<?php

namespace BlogBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLikes()
    {

        $query = $this->getEntityManager()
            ->createQuery("select count(r.idrate) as cnt from AppBundle:Rating r WHERE r.type='Like'");
        return $query->getResult();

    }

    public function getRating($iduser,$idarticle)
    {

        $query = $this->createQueryBuilder('r')
            ->where('r.user = :iduser')
            ->andWhere('r.article = :idarticle')
            ->setParameters(array(
                    'iduser'=>$iduser,
                    'idarticle'=>$idarticle,
                )
            )
            ->getQuery();
        return $query->getResult();
    }



    public function getstat()
    {

        $query = $this->getEntityManager()
       ->createQuery("SELECT a.etat,a.idarticle,a.date,a.titre,a.image,a.description, CASE WHEN r.type='Like'THEN r.type ELSE 'none' END as Rated,SUM(CASE WHEN r.type = 'Like' THEN 1 ELSE 0 END ) as likes 
     from AppBundle:Article a LEFT JOIN AppBundle:Rating r with a.idarticle=r.article   GROUP BY a.idarticle ORDER BY r.type");

        return $query->getResult();
    }
}
