<?php

namespace EntretienBundle\Repository;

/**
 * EntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienRepository extends \Doctrine\ORM\EntityRepository
{
    public function BestSellers()
    {
        $dql = $this->createQueryBuilder('Entretien');
        $dql->orderBy('Entretien.ageVelo', 'DESC');
        $query = $dql->getQuery();
        $query->setMaxResults(3);
        return $query->getResult();
    }




}
