<?php

namespace EntretienBundle\Repository;

/**
 * PiecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiecesRepository extends \Doctrine\ORM\EntityRepository
{
}
