<?php

namespace EntretienBundle\Repository;

/**
 * raitinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class raitinRepository extends \Doctrine\ORM\EntityRepository
{
}
