<?php

namespace EntretienBundle\Repository;

/**
 * SelfEntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelfEntretienRepository extends \Doctrine\ORM\EntityRepository
{
}
