offre_homepage:
    path:     /
    defaults: { _controller: OffreBundle:Offre:index }
offre_add:
    path:     /offreadd
    defaults: { _controller: OffreBundle:Offre:add }
offre_show:
    path:     /offreshow
    defaults: { _controller: OffreBundle:Offre:show }
offre_showby:
    path:     /offreshowby/{id}
    defaults: { _controller: OffreBundle:Offre:showby }
offre_show_detail:
    path:     /showoffredetail/{id}
    defaults: { _controller: OffreBundle:Offre:showdetail }

offre_delete:
    path:     /offredelete/{id}
    defaults: { _controller: OffreBundle:Offre:Delete }
offre_Update:
    path:     /offreupdate/{id}
    defaults: { _controller: OffreBundle:Offre:Update }


Conversation_start:
    path:     /Conversationadd/{id}/{iduser}
    defaults: { _controller: OffreBundle:Conversation:start }
Conversation_show:
    path:     /Conversationadd
    defaults: { _controller: OffreBundle:Conversation:show }
